# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  blockchain_multi:

services:
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.4
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=mychannel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - blockchain_multi
    extra_hosts:
      - "orderer.example.com:172.31.39.23"
      - "orderer2.example.com:172.31.44.81"
      - "orderer3.example.com:172.31.38.221"
      - "peer0.org2.example.com:172.31.40.93"
      - "peer1.org2.example.com:172.31.40.93"
      - "zookeeper0:172.31.39.23"
      - "zookeeper1:172.31.44.81"
      - "zookeeper2:172.31.38.221"
      - "kafka0.example.com:172.31.39.23"
      - "kafka1.example.com:172.31.44.81"
      - "kafka2.example.com:172.31.38.221"
      - "kafka3.example.com:172.31.38.221"
      - "ca0.org1.example.com:172.31.39.23"
      - "ca1.org2.example.com:172.31.39.23"
