# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  blockchain_multi:

services:
  ca0.org1.example.com:
    image: hyperledger/fabric-ca:1.4.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${BYFN_CA1_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${BYFN_CA1_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca0.org1.example.com
    networks:
      - blockchain_multi
    extra_hosts:
      - "cli:172.31.40.93"
      - "peer0.org2.example.com:172.31.40.93"
      - "peer1.org2.example.com:172.31.40.93"
      - "peer0.org1.example.com:172.31.34.29"
      - "peer1.org1.example.com:172.31.34.29"
      - "zookeeper1:172.31.44.81"
      - "zookeeper2:172.31.38.221"
      - "kafka1.example.com:172.31.44.81"
      - "kafka2.example.com:172.31.38.221"
      - "kafka3.example.com:172.31.38.221"
      - "orderer2.example.com:172.31.44.81"
      - "orderer3.examole.com:172.31.38.221"

  ca1.org2.example.com:
    image: hyperledger/fabric-ca:1.4.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${BYFN_CA2_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${BYFN_CA2_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca1.org2.example.com
    networks:
      - blockchain_multi
    extra_hosts:
      - "cli:172.31.40.93"
      - "peer0.org2.example.com:172.31.40.93"
      - "peer1.org2.example.com:172.31.40.93"
      - "peer0.org1.example.com:172.31.34.29"
      - "peer1.org1.example.com:172.31.34.29"
      - "zookeeper1:172.31.44.81"
      - "zookeeper2:172.31.38.221"
      - "kafka1.example.com:172.31.44.81"
      - "kafka2.example.com:172.31.38.221"
      - "kafka3.example.com:172.31.38.221"
      - "orderer2.example.com:172.31.44.81"
      - "orderer3.examole.com:172.31.38.221"
